### ISSUE TITLE
新版发帖按钮消失

### ISSUE THREAD

**Issue by LetMeDecay** [LYLLLRH/nodebb-plugin-reply-to-see#2]
![sp160802_122443.png](https://ooo.0o0.ooo/2016/08/01/57a021040b14c.png)
升级到1.1.0之后，好像改了东西
以前的隐藏回复还是可用的

**Comment by clearw5** [comment]
@DkWyatt 后来怎么解决的

**Comment by LetMeDecay** [comment]
> @DkWyatt 后来怎么解决的

没解决，删了
官方的钩子老是更新，懒得弄了
